/**
 * Email Service - Nodemailer Integration
 * Sends formatted email reports
 */

import nodemailer from 'nodemailer';
import dotenv from 'dotenv';

dotenv.config();

// Create transporter with connection pooling
const createTransporter = () => {
    // Check if we have SMTP configuration
    if (process.env.SMTP_HOST && process.env.SMTP_USER && process.env.SMTP_PASS) {
        return nodemailer.createTransport({
            host: process.env.SMTP_HOST,
            port: parseInt(process.env.SMTP_PORT || '587'),
            secure: process.env.SMTP_SECURE === 'true',
            auth: {
                user: process.env.SMTP_USER,
                pass: process.env.SMTP_PASS
            },
            pool: true,
            maxConnections: 5,
            maxMessages: 100,
            rateLimit: 10
        });
    }

    // For development/testing, use ethereal (fake SMTP)
    return null;
};

/**
 * Convert markdown-style text to HTML
 * @param {string} text - Markdown-style text
 * @returns {string} HTML formatted text
 */
function textToHtml(text) {
    let html = text
        // Headers
        .replace(/^### (.+)$/gm, '<h3>$1</h3>')
        .replace(/^## (.+)$/gm, '<h2>$1</h2>')
        .replace(/^# (.+)$/gm, '<h1>$1</h1>')
        // Bold
        .replace(/\*\*(.+?)\*\*/g, '<strong>$1</strong>')
        // Italic
        .replace(/\*(.+?)\*/g, '<em>$1</em>')
        // Bullet points
        .replace(/^- (.+)$/gm, '<li>$1</li>')
        // Number points
        .replace(/^\d+\. (.+)$/gm, '<li>$1</li>')
        // Line breaks
        .replace(/\n\n/g, '</p><p>')
        .replace(/\n/g, '<br>');

    // Wrap lists
    html = html.replace(/(<li>.*<\/li>)+/gs, match => `<ul>${match}</ul>`);

    // Wrap in paragraphs
    html = `<p>${html}</p>`;

    return html;
}

/**
 * Generate professional HTML email template
 * @param {string} summary - The report summary
 * @returns {string} HTML email content
 */
function generateEmailHtml(summary) {
    const summaryHtml = textToHtml(summary);

    return `
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Sales Insight Report</title>
  <style>
    body {
      font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, 'Helvetica Neue', Arial, sans-serif;
      line-height: 1.6;
      color: #333;
      max-width: 800px;
      margin: 0 auto;
      padding: 20px;
      background-color: #f5f5f5;
    }
    .email-container {
      background-color: #ffffff;
      border-radius: 8px;
      box-shadow: 0 2px 10px rgba(0,0,0,0.1);
      overflow: hidden;
    }
    .header {
      background: linear-gradient(135deg, #667eea 0%, #764ba2 100%);
      color: white;
      padding: 30px;
      text-align: center;
    }
    .header h1 {
      margin: 0;
      font-size: 24px;
      font-weight: 600;
    }
    .header p {
      margin: 10px 0 0 0;
      opacity: 0.9;
      font-size: 14px;
    }
    .content {
      padding: 30px;
    }
    h1, h2, h3 {
      color: #2d3748;
      margin-top: 20px;
      margin-bottom: 10px;
    }
    h1 { font-size: 22px; }
    h2 { font-size: 18px; border-bottom: 2px solid #667eea; padding-bottom: 5px; }
    h3 { font-size: 16px; }
    ul {
      padding-left: 20px;
      margin: 10px 0;
    }
    li {
      margin: 5px 0;
    }
    strong {
      color: #667eea;
    }
    .footer {
      background-color: #f8f9fa;
      padding: 20px 30px;
      text-align: center;
      font-size: 12px;
      color: #718096;
      border-top: 1px solid #e2e8f0;
    }
    .footer a {
      color: #667eea;
      text-decoration: none;
    }
    .timestamp {
      font-size: 12px;
      color: #a0aec0;
      text-align: right;
      padding: 10px 30px;
      background-color: #f8f9fa;
    }
  </style>
</head>
<body>
  <div class="email-container">
    <div class="header">
      <h1>📊 Sales Insight Report</h1>
      <p>AI-Generated Executive Summary</p>
    </div>
    
    <div class="timestamp">
      Generated on ${new Date().toLocaleDateString('en-US', {
        weekday: 'long',
        year: 'numeric',
        month: 'long',
        day: 'numeric',
        hour: '2-digit',
        minute: '2-digit'
    })}
    </div>
    
    <div class="content">
      ${summaryHtml}
    </div>
    
    <div class="footer">
      <p>This report was automatically generated by <strong>Sales Insight Automator</strong></p>
      <p>Powered by AI • Built with ❤️ by Rabbitt AI</p>
    </div>
  </div>
</body>
</html>
`;
}

/**
 * Send email report
 * @param {string} recipient - Recipient email address
 * @param {string} summary - Report summary content
 * @param {string} subject - Email subject
 */
export async function sendEmailReport(recipient, summary, subject = 'Sales Insight Report') {
    const transporter = createTransporter();

    // If no transporter configured, throw error in production
    if (!transporter) {
        // For development, just log and return success
        if (process.env.NODE_ENV !== 'production') {
            console.log('📧 Email would be sent to:', recipient);
            console.log('📧 Subject:', subject);
            console.log('📧 Summary preview:', summary.substring(0, 200) + '...');
            return { success: true, message: 'Email simulated (no SMTP configured)' };
        }
        throw new Error('Email service not configured. Please set SMTP environment variables.');
    }

    const htmlContent = generateEmailHtml(summary);

    const mailOptions = {
        from: process.env.SMTP_FROM || process.env.SMTP_USER,
        to: recipient,
        subject: `📊 ${subject}`,
        text: summary, // Plain text fallback
        html: htmlContent
    };

    try {
        const info = await transporter.sendMail(mailOptions);
        console.log('✅ Email sent successfully:', info.messageId);
        console.log('📧 To:', recipient);
        return { success: true, messageId: info.messageId };
    } catch (error) {
        console.error('❌ Email send error:', error.message);

        // Provide more specific error messages
        let errorMessage = 'Failed to send email';
        if (error.code === 'EAUTH') {
            errorMessage = 'Authentication failed. Check your email and app password';
        } else if (error.code === 'ECONNECTION') {
            errorMessage = 'Connection failed. Check your SMTP settings';
        } else {
            errorMessage = `Failed to send email: ${error.message}`;
        }

        throw new Error(errorMessage);
    }
}
